---
- hosts: dev
  become: true
  become_user: root
  vars:
    password: pwd
    userid: 1222
    sgrp: 
    comments: new user
    username: testuser
    pgrp: 
    hme: 
  tasks:
    - name: Check if the user already exists
      shell: id {{ username }}
      register: user_check
      ignore_errors: yes
    - debug: msg=" USername {{ username }} already exists on {{ ansible_hostname }}"
      when: user_check.rc == 0

    - name: User creation
      user: name={{ username }} uid={{ userid}} home={{ hme }} password={{ password }} group={{ pgrp}} groups={{ sgrp }} append=yes
      when: user_check.rc != 0
      register: usercreation
    - debug: msg="UserName {{ username }} has been created on {{ ansible_hostname }}"
      when: usercreation.changed